"use client";

import { useState, useEffect, createContext, useContext, useCallback } from 'react';

// Définir les langues prises en charge
export type Language = 'fr' | 'en' | 'es' | 'de' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string; // Fonction de traduction simplifiée
}

// Créer un contexte de langue avec des valeurs par défaut
const LanguageContext = createContext<LanguageContextType>({
  language: 'fr',
  setLanguage: () => {},
  t: (key: string) => key,
});

// Traductions de base (à développer davantage selon les besoins)
const translations: Record<Language, Record<string, string>> = {
  fr: {
    'home': 'Accueil',
    'destinations': 'Destinations',
    'about': 'À propos',
    'contact': 'Contact',
    'login': 'Se connecter',
    'logout': 'Se déconnecter',
    'search': 'Rechercher',
    'personalizedTrip': 'Votre voyage personnalisé, conçu pour vous',
    'personalizedTripDescription': 'Des itinéraires adaptés à vos intérêts, vos préférences et votre style de voyage.',
    'whereDoYouWantToGo': 'Où voulez-vous aller ?',
    'date': 'Quand ?',
    'howLong': 'Combien de temps ?',
    'getStarted': 'Commencer',
    'customizedItineraries': 'Itinéraires personnalisés',
    'customizedItinerariesDescription': 'Recevez un itinéraire détaillé pour répondre à vos intérêts et préférences.',
    'expertPlanning': 'Planification experte',
    'expertPlanningDescription': "Nos spécialistes utilisent leurs connaissances pour concevoir votre voyage parfait.",
    'seamlessExperience': 'Expérience fluide',
    'seamlessExperienceDescription': "Profitez d'un voyage sans tracas avec des réservations et des détails gérés pour vous.",
    'footerText': '© 2025 ItinaryMe. Tous droits réservés.',
    'dashboard': 'Tableau de bord',
    'guests': 'Voyageurs',
    'myTrips': 'Mes voyages',
    'howItWorks': 'Comment ça marche',
    'aboutUs': 'À propos de nous',
    'popularDestinations': 'Destinations populaires',
    // Contact page translations
    'contactUs': 'Contactez-nous',
    'contactDescription': 'Vous avez des questions ou des suggestions ? N\'hésitez pas à nous contacter.',
    'fullName': 'Nom complet',
    'email': 'Email',
    'message': 'Message',
    'sendMessage': 'Envoyer le message',
    'sending': 'Envoi en cours...',
    'messageSent': 'Message envoyé !',
    'thankYouMessage': 'Merci de nous avoir contactés. Nous vous répondrons dans les plus brefs délais.',
    'sendAnotherMessage': 'Envoyer un autre message',
    'fillAllFields': 'Veuillez remplir tous les champs.',
    'errorOccurred': 'Une erreur est survenue. Veuillez réessayer plus tard.',
    'contactInfo': 'Informations de contact',
    'phone': 'Téléphone',
    'address': 'Adresse',
    'openingHours': 'Heures d\'ouverture',
    'mondayFriday': 'Lundi - Vendredi',
    'saturday': 'Samedi',
    'sunday': 'Dimanche',
    'closed': 'Fermé',
    // How it works page translations
    'howItWorksDescription': 'Découvrez comment ItinaryMe révolutionne la façon dont vous planifiez vos voyages, en seulement quelques étapes simples.',
    'sharePreferences': 'Partagez vos envies',
    'sharePreferencesDescription': 'Dites-nous où vous souhaitez aller, quand et ce que vous aimez. Plus vous nous donnez d\'informations, plus nous pouvons personnaliser votre expérience.',
    'aiCreatesItinerary': 'Notre IA crée votre itinéraire',
    'aiCreatesItineraryDescription': 'Notre intelligence artificielle avancée crée un itinéraire jour par jour, adapté à vos préférences, à votre budget et au temps dont vous disposez.',
    'customizeAndTravel': 'Personnalisez et voyagez',
    'customizeAndTravelDescription': 'Affinez votre itinéraire jusqu\'à ce qu\'il soit parfait, puis emportez-le avec vous. Accédez à vos plans à tout moment, même hors ligne pendant votre voyage.',
    'features': 'Nos fonctionnalités',
    'customizedItinerariesFeature': 'Itinéraires personnalisés',
    'customizedItinerariesFeatureDescription': 'Des plans de voyage adaptés à vos intérêts, pas des itinéraires génériques. Découvrez les sites incontournables et les joyaux cachés.',
    'quickPlanning': 'Planification rapide',
    'quickPlanningDescription': 'Obtenez un itinéraire complet en quelques minutes, pas en heures. Notre IA fait le travail difficile pour vous.',
    'budgetOptions': 'Options adaptées au budget',
    'budgetOptionsDescription': 'Des suggestions qui respectent votre budget, qu\'il soit serré ou généreux. Profitez au maximum de chaque euro dépensé.',
    'mapsDirections': 'Cartes et directions',
    'mapsDirectionsDescription': 'Des cartes interactives et des instructions de navigation intégrées pour vous aider à vous déplacer sans stress dans des lieux inconnus.',
    'readyToPlan': 'Prêt à planifier votre aventure ?',
    'startTodayDescription': 'Commencez dès aujourd\'hui et découvrez à quel point la planification de voyage peut être simple et agréable.',
    'planMyTrip': 'Planifier mon voyage',
    // About page translations
    'aboutDescription': 'Découvrez comment nous transformons la façon dont vous planifiez vos voyages',
    'ourMission': 'Notre mission',
    'ourMissionDescription1': 'Chez ItinaryMe, notre mission est de simplifier la planification de voyage en offrant une plateforme intuitive qui combine technologie et expertise humaine.',
    'ourMissionDescription2': 'Nous croyons que chaque voyage devrait être une expérience unique, adaptée à vos préférences personnelles et dépourvue des tracas habituels liés à la planification.',
    'ourHistory': 'Notre histoire',
    'ourHistoryDescription1': 'ItinaryMe est né en 2025 de la frustration de ses fondateurs face à la complexité de planifier des voyages mémorables sans y passer des heures.',
    'ourHistoryDescription2': 'Depuis, nous avons aidé des milliers de voyageurs à créer des itinéraires personnalisés qui correspondent parfaitement à leurs envies et à leur budget.',
    'howItFunctions': 'Comment ça fonctionne',
    'shareYourPreferences': 'Partagez vos préférences',
    'shareYourPreferencesDescription': 'Indiquez-nous votre destination, dates de voyage et vos centres d\'intérêt.',
    'personalizedAIAssistant': 'Assistant IA personnalisé',
    'personalizedAIAssistantDescription': 'Notre assistant intelligent créera un itinéraire adapté à vos préférences.',
    'enjoyYourTrip': 'Profitez de votre voyage',
    'enjoyYourTripDescription': 'Accédez à votre itinéraire détaillé et modifiez-le à tout moment.',
    'readyToPlanYourNextTrip': 'Prêt à planifier votre prochain voyage ?',
    'joinThousandsOfTravelers': 'Rejoignez des milliers de voyageurs qui ont déjà simplifié leur planification avec ItinaryMe.',
    'startYourItinerary': 'Commencer votre itinéraire',
    // Destinations page translations
    'destinationsDescription': 'Découvrez des destinations de rêve du monde entier et commencez à planifier votre prochain voyage',
    'searchDestination': 'Rechercher une destination...',
    'filterBySeason': 'Filtrer par saison :',
    'allSeasons': 'Toutes les saisons',
    'spring': 'Printemps',
    'summer': 'Été',
    'autumn': 'Automne',
    'winter': 'Hiver',
    'noDestinationsFound': 'Aucune destination ne correspond à vos critères. Veuillez essayer une autre recherche.',
    'cantFindDreamDestination': 'Vous ne trouvez pas la destination de vos rêves ? Contactez-nous et nous vous aiderons à la planifier.',
    // Destinations translations
    'destination_paris': 'Paris, France',
    'destination_paris_desc': "La ville de l'amour, Paris regorge de monuments emblématiques comme la Tour Eiffel, le Louvre et Notre-Dame. Découvrez l'art, la gastronomie et l'architecture unique de cette capitale européenne.",
    'destination_tokyo': 'Tokyo, Japon',
    'destination_tokyo_desc': "Mélange fascinant de traditions anciennes et de technologies futuristes, Tokyo est une métropole vibrante offrant une expérience culturelle unique, une cuisine raffinée et des quartiers aux atmosphères contrastées.",
    'destination_new_york': 'New York, États-Unis',
    'destination_new_york_desc': 'La ville qui ne dort jamais offre une énergie incomparable, des gratte-ciels emblématiques, des musées de classe mondiale, une scène culturelle dynamique et des quartiers diversifiés à explorer.',
    'destination_rome': 'Rome, Italie',
    'destination_rome_desc': "La Ville Éternelle est un musée à ciel ouvert où l'histoire antique côtoie la vie moderne. Découvrez les vestiges de l'Empire romain, la cuisine italienne authentique et l'ambiance unique des places et fontaines.",
    'destination_bali': 'Bali, Indonésie',
    'destination_bali_desc': "L'île des dieux offre des plages paradisiaques, des rizières en terrasses, des temples spirituels et une culture riche. Bali est idéale pour se détendre, pratiquer le yoga ou partir à l'aventure.",
    'destination_barcelona': 'Barcelone, Espagne',
    'destination_barcelona_desc': 'Avec son architecture unique de Gaudí, ses plages urbaines, sa cuisine catalane et son ambiance festive, Barcelone est une destination méditerranéenne parfaite pour un city-break culturel.',
    'destination_marrakech': 'Marrakech, Maroc',
    'destination_marrakech_desc': "La ville rouge vous plonge dans les couleurs et parfums de l'Afrique du Nord. Entre souks animés, palais majestueux et jardins luxuriants, Marrakech offre une immersion culturelle intense.",
    'destination_kyoto': 'Kyoto, Japon',
    'destination_kyoto_desc': "Als ehemalige kaiserliche Hauptstadt verkörpert Kyoto die traditionelle Seele Japans mit seinen Zen-Tempeln, japanischen Gärten, Shinto-Schreinen und Geisha-Häusern. Ein Eintauchen in japanische Gelassenheit und Ästhetik.",
    'destination_santorini': 'Santorin, Grèce',
    'destination_santorini_desc': 'Cette île cyclique offre un paysage à couper le souffle avec ses maisons blanches à dômes bleus surplombant la mer Égée. Profitez des couchers de soleil spectaculaires, des plages volcaniques et de la gastronomie grecque.',
    'best_time_to_visit': 'Meilleure période pour visiter',
    'highlights': 'Points forts',
    // ---- Landing page (lp_*) ----
    'lp_navCta': 'Commencer',
    'lp_navPlan': 'Planifier un voyage',
    'lp_badge': 'Nouveau · Agent de voyage IA',
    'lp_heroTitle': 'Racontez votre voyage.',
    'lp_heroTitleHighlight': 'On s\'occupe du reste.',
    'lp_heroSubtitle': "Notre IA conçoit votre itinéraire jour par jour, compare vols et hôtels en temps réel, et vous réserve tout au meilleur prix. En moins d'une minute.",
    'lp_heroCta': 'Créer mon voyage',
    'lp_heroCtaSecondary': 'Voir comment ça marche',
    'lp_fieldWhere': 'Destination',
    'lp_fieldDeparture': 'Départ',
    'lp_fieldReturn': 'Retour',
    'lp_socialProof': '12 000+ voyageurs conquis',
    'lp_rating': '4,9/5 en satisfaction',
    'lp_mockUser': 'Une semaine à Lisbonne en octobre, 1 200 € pour deux, plutôt food et culture.',
    'lp_mockStep1': 'Recherche des vols Paris → Lisbonne',
    'lp_mockStep2': 'Comparaison de 128 hôtels disponibles',
    'lp_mockStep3': 'Construction de l\'itinéraire sur 7 jours',
    'lp_mockAgent': "Voici votre séjour : 7 jours à Lisbonne avec Alfama, Belém, une journée à Sintra et 5 tables réservées. Total 1 042 €, soit 158 € sous votre budget.",
    'lp_mockFlightTag': 'Vol aller-retour',
    'lp_mockFlightTitle': 'Paris CDG → Lisbonne',
    'lp_mockFlightSub': '2 h 45 · direct · 12 oct.',
    'lp_mockHotelTag': 'Hôtel',
    'lp_mockHotelTitle': 'Baixa Boutique Hotel',
    'lp_mockHotelSub': '4★ · centre historique · petit-déj. inclus',
    'lp_mockBudget': 'Budget total',
    'lp_mockFloatingTag': 'Itinéraire',
    'lp_mockFloatingValue': '7 jours planifiés',
    'lp_mockFloating2Tag': 'Économies',
    'lp_mockFloating2Value': '158 € sous budget',
    'lp_statsTitle': 'Connecté aux meilleures sources de voyage',
    'lp_stat1': 'compagnies aériennes connectées',
    'lp_stat2': 'hôtels et logements comparés',
    'lp_stat3': 'pour un itinéraire complet',
    'lp_stat4': 'note moyenne des voyageurs',
    'lp_stepsTag': 'Comment ça marche',
    'lp_stepsTitle': 'Trois étapes. Zéro prise de tête.',
    'lp_stepsSubtitle': 'Plus d\'onglets à empiler, plus de tableurs. Vous décrivez, on organise.',
    'lp_step1Title': 'Décrivez vos envies',
    'lp_step1Desc': 'En une phrase : la destination, les dates, le budget, l\'ambiance. Comme si vous parliez à un ami qui connaît tout.',
    'lp_step2Title': 'L\'IA compose votre voyage',
    'lp_step2Desc': 'Elle cherche les vols, compare les hôtels, sélectionne les activités et assemble un itinéraire cohérent, heure par heure.',
    'lp_step3Title': 'Réservez en un clic',
    'lp_step3Desc': 'Tout arrive dans votre panier. Un seul paiement sécurisé et vos confirmations vous attendent dans votre espace.',
    'lp_featuresTag': 'Fonctionnalités',
    'lp_featuresTitle': 'Un copilote de voyage, pas un moteur de recherche',
    'lp_featuresSubtitle': 'Tout ce qu\'il faut pour passer de l\'envie au départ, réuni au même endroit.',
    'lp_feat1Title': 'Un itinéraire jour par jour, vraiment pensé pour vous',
    'lp_feat1Desc': 'Chaque journée est équilibrée : temps de trajet, horaires d\'ouverture, pauses déjeuner. Modifiable à tout moment d\'un simple message.',
    'lp_feat1Day1': 'Jour 1 · Alfama & Miradouros',
    'lp_feat1Day1Detail': 'Tram 28, château São Jorge, dîner fado',
    'lp_feat1Day2': 'Jour 2 · Belém',
    'lp_feat1Day2Detail': 'Monastère des Hiéronymites, pastéis de Belém',
    'lp_feat1Day3': 'Jour 3 · Sintra',
    'lp_feat1Day3Detail': 'Palais da Pena, Quinta da Regaleira',
    'lp_feat2Title': 'Vols en temps réel',
    'lp_feat2Desc': 'Prix et disponibilités en direct sur des centaines de compagnies, sans onglet supplémentaire.',
    'lp_feat3Title': 'Hôtels et adresses triés',
    'lp_feat3Desc': 'Des logements sélectionnés selon votre budget et votre quartier idéal, avis à l\'appui.',
    'lp_feat4Title': 'Paiement sécurisé',
    'lp_feat4Desc': 'Vols, hôtels et activités dans un seul panier, réglés en une fois via Stripe.',
    'lp_feat5Title': 'Budget maîtrisé',
    'lp_feat5Desc': 'Le total se met à jour en direct : vous savez toujours où vous en êtes avant de valider.',
    'lp_feat6Title': 'Disponible en 5 langues',
    'lp_feat6Desc': 'ItinaryMe parle votre langue et s\'adapte automatiquement à votre pays et à votre devise.',
    'lp_destTag': 'Inspiration',
    'lp_destTitle': 'Où partez-vous cette année ?',
    'lp_destSubtitle': 'Choisissez une destination, l\'IA construit le voyage complet en quelques secondes.',
    'lp_destCta': 'Toutes les destinations',
    'lp_testiTag': 'Témoignages',
    'lp_testiTitle': 'Ils ont laissé l\'IA planifier',
    'lp_testi1': "J'ai décrit mon voyage en deux phrases et j'ai reçu un itinéraire de 10 jours au Japon mieux ficelé que celui que j'avais mis trois week-ends à préparer.",
    'lp_testi1Name': 'Camille L.',
    'lp_testi1Role': 'Voyage au Japon, 10 jours',
    'lp_testi2': "Le comparateur de vols intégré m'a fait économiser 240 € sur les billets. Et je n'ai jamais quitté l'application pour réserver.",
    'lp_testi2Name': 'Marc R.',
    'lp_testi2Role': 'Week-end à Barcelone',
    'lp_testi3': "Voyager à quatre avec deux enfants, c'était un casse-tête. Là, tout était calé : horaires, distances, restaurants adaptés.",
    'lp_testi3Name': 'Amélie D.',
    'lp_testi3Role': 'Vacances en famille au Portugal',
    'lp_ctaTitle': 'Votre prochain voyage commence maintenant',
    'lp_ctaSubtitle': 'Créez votre premier itinéraire gratuitement. Vous ne payez que ce que vous réservez.',
    'lp_ctaButton': 'Créer mon itinéraire',
    'lp_ctaSecondary': 'Découvrir la démo',
    'lp_ctaPerk1': 'Sans carte bancaire',
    'lp_ctaPerk2': 'Itinéraire prêt en 60 secondes',
    'lp_ctaPerk3': 'Annulation selon les conditions du prestataire',
    // Footer translations
    'footer_about': 'À propos',
    'footer_ourStory': 'Notre histoire',
    'footer_howItWorks': 'Comment ça marche',
    'footer_testimonials': 'Témoignages',
    'footer_destinations': 'Destinations',
    'footer_popular': 'Populaires',
    'footer_bySeason': 'Par saison',
    'footer_allDestinations': 'Toutes les destinations',
    'footer_contact': 'Contact',
    'footer_contactUs': 'Nous contacter',
    'footer_support': 'Support',
    'footer_faq': 'FAQ',
    'footer_copyright': '© 2025 ItinaryMe. Tous droits réservés.',
    'footer_privacy': 'Confidentialité',
    'footer_terms': 'Conditions',
    'footer_cookies': 'Cookies',
    'footer_tagline': 'Votre partenaire de confiance pour planifier des voyages inoubliables et personnalisés.',
  },
  en: {
    'home': 'Home',
    'destinations': 'Destinations',
    'about': 'About',
    'contact': 'Contact',
    'login': 'Login',
    'logout': 'Logout',
    'search': 'Search',
    'personalizedTrip': 'Your personalized trip, designed for you',
    'personalizedTripDescription': 'Tailored itineraries to match your unique interests, preferences, and travel style.',
    'whereDoYouWantToGo': 'Where do you want to go?',
    'date': 'When?',
    'howLong': 'How long?',
    'getStarted': 'Get Started',
    'customizedItineraries': 'Customized Itineraries',
    'customizedItinerariesDescription': 'Receive a day-by-day itinerary crafted to your interests and preferences.',
    'expertPlanning': 'Expert Planning',
    'expertPlanningDescription': 'Our travel specialists use their knowledge to create your perfect trip.',
    'seamlessExperience': 'Seamless Experience',
    'seamlessExperienceDescription': 'Enjoy a hassle-free journey with bookings and details arranged for you.',
    'footerText': '© 2025 ItinaryMe. All rights reserved.',
    'dashboard': 'Dashboard',
    'guests': 'Guests',
    'myTrips': 'My trips',
    'howItWorks': 'How it works',
    'aboutUs': 'About Us',
    'popularDestinations': 'Popular Destinations',
    // Contact page translations
    'contactUs': 'Contact Us',
    'contactDescription': 'Have questions or suggestions? Feel free to contact us.',
    'fullName': 'Full Name',
    'email': 'Email',
    'message': 'Message',
    'sendMessage': 'Send Message',
    'sending': 'Sending...',
    'messageSent': 'Message Sent!',
    'thankYouMessage': 'Thank you for contacting us. We will get back to you shortly.',
    'sendAnotherMessage': 'Send Another Message',
    'fillAllFields': 'Please fill in all fields.',
    'errorOccurred': 'An error occurred. Please try again later.',
    'contactInfo': 'Contact Information',
    'phone': 'Phone',
    'address': 'Address',
    'openingHours': 'Opening Hours',
    'mondayFriday': 'Monday - Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'closed': 'Closed',
    // How it works page translations
    'howItWorksDescription': 'Discover how ItinaryMe revolutionizes the way you plan your travels, in just a few simple steps.',
    'sharePreferences': 'Share Your Preferences',
    'sharePreferencesDescription': 'Tell us where you want to go, when, and what you like. The more information you give us, the more we can personalize your experience.',
    'aiCreatesItinerary': 'Our AI Creates Your Itinerary',
    'aiCreatesItineraryDescription': 'Our advanced artificial intelligence creates a day-by-day itinerary, tailored to your preferences, budget, and available time.',
    'customizeAndTravel': 'Customize and Travel',
    'customizeAndTravelDescription': 'Refine your itinerary until it\'s perfect, then take it with you. Access your plans anytime, even offline during your trip.',
    'features': 'Our Features',
    'customizedItinerariesFeature': 'Customized Itineraries',
    'customizedItinerariesFeatureDescription': 'Travel plans tailored to your interests, not generic itineraries. Discover must-see sites and hidden gems.',
    'quickPlanning': 'Quick Planning',
    'quickPlanningDescription': 'Get a complete itinerary in minutes, not hours. Our AI does the hard work for you.',
    'budgetOptions': 'Budget-Friendly Options',
    'budgetOptionsDescription': 'Suggestions that respect your budget, whether tight or generous. Make the most of every dollar spent.',
    'mapsDirections': 'Maps and Directions',
    'mapsDirectionsDescription': 'Built-in interactive maps and navigation instructions to help you move stress-free in unfamiliar places.',
    'readyToPlan': 'Ready to Plan Your Adventure?',
    'startTodayDescription': 'Start today and discover how easy and enjoyable travel planning can be.',
    'planMyTrip': 'Plan My Trip',
    // About page translations
    'aboutDescription': 'Discover how we transform the way you plan your travels',
    'ourMission': 'Our Mission',
    'ourMissionDescription1': 'At ItinaryMe, our mission is to simplify travel planning by offering an intuitive platform that combines technology and human expertise.',
    'ourMissionDescription2': 'We believe that every trip should be a unique experience, tailored to your personal preferences and free from the usual planning hassles.',
    'ourHistory': 'Our History',
    'ourHistoryDescription1': 'ItinaryMe was born in 2025 from its founders\' frustration with the complexity of planning memorable trips without spending hours on it.',
    'ourHistoryDescription2': 'Since then, we have helped thousands of travelers create personalized itineraries that perfectly match their desires and budget.',
    'howItFunctions': 'How It Works',
    'shareYourPreferences': 'Share Your Preferences',
    'shareYourPreferencesDescription': 'Tell us your destination, travel dates, and interests.',
    'personalizedAIAssistant': 'Personalized AI Assistant',
    'personalizedAIAssistantDescription': 'Our intelligent assistant will create an itinerary tailored to your preferences.',
    'enjoyYourTrip': 'Enjoy Your Trip',
    'enjoyYourTripDescription': 'Access your detailed itinerary and modify it at any time.',
    'readyToPlanYourNextTrip': 'Ready to plan your next trip?',
    'joinThousandsOfTravelers': 'Join thousands of travelers who have already simplified their planning with ItinaryMe.',
    'startYourItinerary': 'Start Your Itinerary',
    // Destinations page translations
    'destinationsDescription': 'Discover dream destinations from around the world and start planning your next trip',
    'searchDestination': 'Search for a destination...',
    'filterBySeason': 'Filter by season:',
    'allSeasons': 'All seasons',
    'spring': 'Spring',
    'summer': 'Summer',
    'autumn': 'Autumn',
    'winter': 'Winter',
    'noDestinationsFound': 'No destinations match your criteria. Please try another search.',
    'cantFindDreamDestination': 'Can\'t find your dream destination? Contact us and we\'ll help you plan it.',
    // Destinations translations
    'destination_paris': 'Paris, France',
    'destination_paris_desc': "The city of love, Paris is filled with iconic landmarks like the Eiffel Tower, the Louvre, and Notre Dame. Discover the art, cuisine, and unique architecture of this European capital.",
    'destination_tokyo': 'Tokyo, Japan',
    'destination_tokyo_desc': "A fascinating blend of ancient traditions and futuristic technology, Tokyo is a vibrant metropolis offering a unique cultural experience, refined cuisine, and neighborhoods with contrasting atmospheres.",
    'destination_new_york': 'New York, United States',
    'destination_new_york_desc': 'The city that never sleeps offers unparalleled energy, iconic skyscrapers, world-class museums, a dynamic cultural scene, and diverse neighborhoods to explore.',
    'destination_rome': 'Rome, Italy',
    'destination_rome_desc': "The Eternal City is an open-air museum where ancient history meets modern life. Discover the remnants of the Roman Empire, authentic Italian cuisine, and the unique ambiance of squares and fountains.",
    'destination_bali': 'Bali, Indonesia',
    'destination_bali_desc': "The island of gods offers paradise beaches, terraced rice fields, spiritual temples, and a rich culture. Bali is ideal for relaxation, yoga, or adventure.",
    'destination_barcelona': 'Barcelona, Spain',
    'destination_barcelona_desc': 'With its unique Gaudí architecture, urban beaches, Catalan cuisine, and festive atmosphere, Barcelona is a perfect Mediterranean destination for a cultural city break.',
    'destination_marrakech': 'Marrakech, Morocco',
    'destination_marrakech_desc': "La ville rouge vous plonge dans les couleurs et parfums de l'Afrique du Nord. Entre souks animés, palais majestueux et jardins luxuriants, Marrakech offre une immersion culturelle intense.",
    'destination_kyoto': 'Kyoto, Japan',
    'destination_kyoto_desc': "Als ehemalige kaiserliche Hauptstadt verkörpert Kyoto die traditionelle Seele Japans mit seinen Zen-Tempeln, japanischen Gärten, Shinto-Schreinen und Geisha-Häusern. Ein Eintauchen in japanische Gelassenheit und Ästhetik.",
    'destination_santorini': 'Santorini, Greece',
    'destination_santorini_desc': 'This Cycladic island offers breathtaking landscapes with its white houses with blue domes overlooking the Aegean Sea. Enjoy spectacular sunsets, volcanic beaches, and Greek gastronomy.',
    'best_time_to_visit': 'Best time to visit',
    'highlights': 'Highlights',
    // ---- Landing page (lp_*) ----
    'lp_navCta': 'Get started',
    'lp_navPlan': 'Plan a trip',
    'lp_badge': 'New · AI travel agent',
    'lp_heroTitle': 'Describe your trip.',
    'lp_heroTitleHighlight': 'We handle the rest.',
    'lp_heroSubtitle': 'Our AI builds your day-by-day itinerary, compares flights and hotels in real time, and books everything at the best price. In under a minute.',
    'lp_heroCta': 'Create my trip',
    'lp_heroCtaSecondary': 'See how it works',
    'lp_fieldWhere': 'Destination',
    'lp_fieldDeparture': 'Departure',
    'lp_fieldReturn': 'Return',
    'lp_socialProof': '12,000+ happy travelers',
    'lp_rating': '4.9/5 satisfaction',
    'lp_mockUser': 'A week in Lisbon in October, €1,200 for two, mostly food and culture.',
    'lp_mockStep1': 'Searching flights Paris → Lisbon',
    'lp_mockStep2': 'Comparing 128 available hotels',
    'lp_mockStep3': 'Building the 7-day itinerary',
    'lp_mockAgent': 'Here is your trip: 7 days in Lisbon with Alfama, Belém, a day in Sintra and 5 tables booked. Total €1,042 — €158 under your budget.',
    'lp_mockFlightTag': 'Round trip',
    'lp_mockFlightTitle': 'Paris CDG → Lisbon',
    'lp_mockFlightSub': '2h45 · direct · Oct 12',
    'lp_mockHotelTag': 'Hotel',
    'lp_mockHotelTitle': 'Baixa Boutique Hotel',
    'lp_mockHotelSub': '4★ · historic centre · breakfast included',
    'lp_mockBudget': 'Total budget',
    'lp_mockFloatingTag': 'Itinerary',
    'lp_mockFloatingValue': '7 days planned',
    'lp_mockFloating2Tag': 'Savings',
    'lp_mockFloating2Value': '€158 under budget',
    'lp_statsTitle': 'Connected to the best travel sources',
    'lp_stat1': 'airlines connected',
    'lp_stat2': 'hotels and stays compared',
    'lp_stat3': 'for a complete itinerary',
    'lp_stat4': 'average traveler rating',
    'lp_stepsTag': 'How it works',
    'lp_stepsTitle': 'Three steps. Zero headaches.',
    'lp_stepsSubtitle': 'No more stacked tabs, no more spreadsheets. You describe, we organize.',
    'lp_step1Title': 'Describe what you want',
    'lp_step1Desc': 'One sentence: destination, dates, budget, vibe. Just like talking to a friend who knows every corner of the world.',
    'lp_step2Title': 'The AI composes your trip',
    'lp_step2Desc': 'It searches flights, compares hotels, picks activities and assembles a coherent itinerary, hour by hour.',
    'lp_step3Title': 'Book in one click',
    'lp_step3Desc': 'Everything lands in your cart. One secure payment, and your confirmations are waiting in your account.',
    'lp_featuresTag': 'Features',
    'lp_featuresTitle': 'A travel copilot, not a search engine',
    'lp_featuresSubtitle': 'Everything you need to go from craving a trip to boarding, all in one place.',
    'lp_feat1Title': 'A day-by-day itinerary genuinely built for you',
    'lp_feat1Desc': 'Every day is balanced: travel times, opening hours, lunch breaks. Change anything at any time with a simple message.',
    'lp_feat1Day1': 'Day 1 · Alfama & Miradouros',
    'lp_feat1Day1Detail': 'Tram 28, São Jorge castle, fado dinner',
    'lp_feat1Day2': 'Day 2 · Belém',
    'lp_feat1Day2Detail': 'Jerónimos Monastery, pastéis de Belém',
    'lp_feat1Day3': 'Day 3 · Sintra',
    'lp_feat1Day3Detail': 'Pena Palace, Quinta da Regaleira',
    'lp_feat2Title': 'Real-time flights',
    'lp_feat2Desc': 'Live prices and availability across hundreds of airlines, without opening another tab.',
    'lp_feat3Title': 'Curated hotels and spots',
    'lp_feat3Desc': 'Stays picked for your budget and your ideal neighbourhood, reviews included.',
    'lp_feat4Title': 'Secure payment',
    'lp_feat4Desc': 'Flights, hotels and activities in a single cart, paid in one go through Stripe.',
    'lp_feat5Title': 'Budget under control',
    'lp_feat5Desc': 'The total updates live, so you always know where you stand before confirming.',
    'lp_feat6Title': 'Available in 5 languages',
    'lp_feat6Desc': 'ItinaryMe speaks your language and adapts automatically to your country and currency.',
    'lp_destTag': 'Inspiration',
    'lp_destTitle': 'Where are you going this year?',
    'lp_destSubtitle': 'Pick a destination and the AI builds the full trip in seconds.',
    'lp_destCta': 'All destinations',
    'lp_testiTag': 'Testimonials',
    'lp_testiTitle': 'They let the AI plan',
    'lp_testi1': 'I described my trip in two sentences and got a 10-day Japan itinerary better put together than the one I spent three weekends on.',
    'lp_testi1Name': 'Camille L.',
    'lp_testi1Role': 'Japan trip, 10 days',
    'lp_testi2': 'The built-in flight comparison saved me €240 on tickets. And I never left the app to book.',
    'lp_testi2Name': 'Marc R.',
    'lp_testi2Role': 'Weekend in Barcelona',
    'lp_testi3': 'Travelling as four with two kids used to be a nightmare. This time everything fit: timings, distances, kid-friendly restaurants.',
    'lp_testi3Name': 'Amélie D.',
    'lp_testi3Role': 'Family holiday in Portugal',
    'lp_ctaTitle': 'Your next trip starts now',
    'lp_ctaSubtitle': 'Build your first itinerary for free. You only pay for what you book.',
    'lp_ctaButton': 'Create my itinerary',
    'lp_ctaSecondary': 'Watch the demo',
    'lp_ctaPerk1': 'No credit card required',
    'lp_ctaPerk2': 'Itinerary ready in 60 seconds',
    'lp_ctaPerk3': 'Cancellation per provider terms',
    // Footer translations
    'footer_about': 'About',
    'footer_ourStory': 'Our Story',
    'footer_howItWorks': 'How It Works',
    'footer_testimonials': 'Testimonials',
    'footer_destinations': 'Destinations',
    'footer_popular': 'Popular',
    'footer_bySeason': 'By Season',
    'footer_allDestinations': 'All Destinations',
    'footer_contact': 'Contact',
    'footer_contactUs': 'Contact Us',
    'footer_support': 'Support',
    'footer_faq': 'FAQ',
    'footer_copyright': '© 2025 ItinaryMe. All rights reserved.',
    'footer_privacy': 'Privacy Policy',
    'footer_terms': 'Terms of Service',
    'footer_cookies': 'Cookies',
    'footer_tagline': 'Your trusted partner for planning unforgettable, personalized trips.',
  },
  es: {
    'home': 'Inicio',
    'destinations': 'Destinos',
    'about': 'Acerca de',
    'contact': 'Contacto',
    'login': 'Iniciar sesión',
    'logout': 'Cerrar sesión',
    'search': 'Buscar',
    'personalizedTrip': 'Su viaje personalizado, diseñado para usted',
    'personalizedTripDescription': 'Itinerarios adaptados a sus intereses, preferencias y estilo de viaje.',
    'whereDoYouWantToGo': '¿Dónde quieres ir?',
    'date': '¿Cuándo?',
    'howLong': '¿Cuánto tiempo?',
    'getStarted': 'Comenzar',
    'customizedItineraries': 'Itinerarios personalizados',
    'customizedItinerariesDescription': 'Reciba un itinerario detallado adaptado a sus intereses y preferencias.',
    'expertPlanning': 'Planificación experta',
    'expertPlanningDescription': 'Nuestros especialistas utilizan sus conocimientos para crear su viaje perfecto.',
    'seamlessExperience': 'Experiencia sin problemas',
    'seamlessExperienceDescription': 'Disfrute de un viaje sin complicaciones con reservas y detalles organizados para usted.',
    'footerText': '© 2025 ItinaryMe. Todos los derechos reservados.',
    'dashboard': 'Panel de control',
    'guests': 'Huéspedes',
    'myTrips': 'Mis viajes',
    'howItWorks': 'Cómo funciona',
    'aboutUs': 'Sobre Nosotros',
    'popularDestinations': 'Destinos Populares',
    // Contact page translations
    'contactUs': 'Contáctenos',
    'contactDescription': '¿Tiene preguntas o sugerencias? No dude en contactarnos.',
    'fullName': 'Nombre completo',
    'email': 'Correo electrónico',
    'message': 'Mensaje',
    'sendMessage': 'Enviar mensaje',
    'sending': 'Enviando...',
    'messageSent': '¡Mensaje enviado!',
    'thankYouMessage': 'Gracias por contactarnos. Nos pondremos en contacto con usted a la brevedad.',
    'sendAnotherMessage': 'Enviar otro mensaje',
    'fillAllFields': 'Por favor complete todos los campos.',
    'errorOccurred': 'Ha ocurrido un error. Por favor, inténtelo de nuevo más tarde.',
    'contactInfo': 'Información de contacto',
    'phone': 'Teléfono',
    'address': 'Dirección',
    'openingHours': 'Horario de atención',
    'mondayFriday': 'Lunes - Viernes',
    'saturday': 'Sábado',
    'sunday': 'Domingo',
    'closed': 'Cerrado',
    // How it works page translations
    'howItWorksDescription': 'Descubra cómo ItinaryMe revoluciona la forma en que planifica sus viajes, en solo unos sencillos pasos.',
    'sharePreferences': 'Comparta sus preferencias',
    'sharePreferencesDescription': 'Díganos dónde quiere ir, cuándo y qué le gusta. Cuanta más información nos proporcione, más podremos personalizar su experiencia.',
    'aiCreatesItinerary': 'Nuestra IA crea su itinerario',
    'aiCreatesItineraryDescription': 'Nuestra avanzada inteligencia artificial crea un itinerario día a día, adaptado a sus preferencias, presupuesto y tiempo disponible.',
    'customizeAndTravel': 'Personalice y viaje',
    'customizeAndTravelDescription': 'Refine su itinerario hasta que sea perfecto, y luego llévelo con usted. Acceda a sus planes en cualquier momento, incluso sin conexión durante su viaje.',
    'features': 'Nuestras características',
    'customizedItinerariesFeature': 'Itinerarios personalizados',
    'customizedItinerariesFeatureDescription': 'Planes de viaje adaptados a sus intereses, no itinerarios genéricos. Descubra lugares de visita obligada y joyas ocultas.',
    'quickPlanning': 'Planificación rápida',
    'quickPlanningDescription': 'Obtenga un itinerario completo en minutos, no en horas. Nuestra IA hace el trabajo duro por usted.',
    'budgetOptions': 'Opciones según presupuesto',
    'budgetOptionsDescription': 'Sugerencias que respetan su presupuesto, ya sea ajustado o generoso. Aproveche al máximo cada euro gastado.',
    'mapsDirections': 'Mapas e indicaciones',
    'mapsDirectionsDescription': 'Mapas interactivos integrados e instrucciones de navegación para ayudarle a moverse sin estrés en lugares desconocidos.',
    'readyToPlan': '¿Listo para planificar su aventura?',
    'startTodayDescription': 'Comience hoy y descubra lo fácil y agradable que puede ser la planificación de viajes.',
    'planMyTrip': 'Planificar mi viaje',
    // About page translations
    'aboutDescription': 'Descubra cómo transformamos la forma en que planifica sus viajes',
    'ourMission': 'Nuestra Misión',
    'ourMissionDescription1': 'En ItinaryMe, nuestra misión es simplificar la planificación de viajes ofreciendo una plataforma intuitiva que combina tecnología y experiencia humana.',
    'ourMissionDescription2': 'Creemos que cada viaje debe ser una experiencia única, adaptada a sus preferencias personales y libre de las molestias habituales de planificación.',
    'ourHistory': 'Nuestra Historia',
    'ourHistoryDescription1': 'ItinaryMe nació en 2025 de la frustración de sus fundadores ante la complejidad de planificar viajes memorables sin pasar horas en ello.',
    'ourHistoryDescription2': 'Desde entonces, hemos ayudado a miles de viajeros a crear itinerarios personalizados que se ajustan perfectamente a sus deseos y presupuesto.',
    'howItFunctions': 'Cómo Funciona',
    'shareYourPreferences': 'Comparta Sus Preferencias',
    'shareYourPreferencesDescription': 'Indíquenos su destino, fechas de viaje y sus intereses.',
    'personalizedAIAssistant': 'Asistente IA Personalizado',
    'personalizedAIAssistantDescription': 'Nuestro asistente inteligente creará un itinerario adaptado a sus preferencias.',
    'enjoyYourTrip': 'Disfrute Su Viaje',
    'enjoyYourTripDescription': 'Acceda a su itinerario detallado y modifíquelo en cualquier momento.',
    'readyToPlanYourNextTrip': '¿Listo para planificar su próximo viaje?',
    'joinThousandsOfTravelers': 'Únase a miles de viajeros que ya han simplificado su planificación con ItinaryMe.',
    'startYourItinerary': 'Comenzar Su Itinerario',
    // Destinations page translations
    'destinationsDescription': 'Descubra destinos de ensueño de todo el mundo y comience a planificar su próximo viaje',
    'searchDestination': 'Buscar un destino...',
    'filterBySeason': 'Filtrar por temporada:',
    'allSeasons': 'Todas las temporadas',
    'spring': 'Primavera',
    'summer': 'Verano',
    'autumn': 'Otoño',
    'winter': 'Invierno',
    'noDestinationsFound': 'Ningún destino coincide con sus criterios. Por favor, intente otra búsqueda.',
    'cantFindDreamDestination': '¿No encuentra su destino soñado? Contáctenos y le ayudaremos a planificarlo.',
    // Destinations translations
    'destination_paris': 'París, Francia',
    'destination_paris_desc': "La ciudad del amor, París está llena de monumentos emblemáticos como la Torre Eiffel, el Louvre y Notre Dame. Descubra el arte, la gastronomía y la arquitectura única de esta capital europea.",
    'destination_tokyo': 'Tokio, Japón',
    'destination_tokyo_desc': "Un affascinante mix di antiche tradizioni e tecnologia futuristica, Tokyo è una metropoli vibrante che offre un'esperienza culturale unica, una cucina raffinata e quartieri con atmosfere contrastanti.",
    'destination_new_york': 'Nueva York, Estados Unidos',
    'destination_new_york_desc': 'La ciudad que nunca duerme offre une énergie senza pari, grattacieli iconiques, musei di livello mondiale, une scène culturelle dynamique et quartiers diversifiés à explorer.',
    'destination_rome': 'Roma, Italia',
    'destination_rome_desc': "La Città Eterna è un museo a cielo aperto dove la storia antica incontra la vita moderna. Scopri i resti dell'Impero Romano, l'autentica cucina italiana e l'atmosfera unica di piazze e fontane.",
    'destination_bali': 'Bali, Indonesia',
    'destination_bali_desc': "La isla degli dei offre spiagge paradisiache, risaie a terrazza, templi spirituali e una ricca cultura. Bali è ideale per rilassarsi, praticare yoga o avventurarsi.",
    'destination_barcelona': 'Barcelona, España',
    'destination_barcelona_desc': 'Con su arquitectura única de Gaudí, playas urbanas, cocina catalana y ambiente festoso, Barcellona è una destinazione mediterránea perfetta per una fuga culturale.',
    'destination_marrakech': 'Marrakesch, Marocco',
    'destination_marrakech_desc': "La ciudad roja te sumerge en los colores y aromas del norte de África. Entre zocos animados, palacios majestuosos y jardines exuberantes, Marrakech ofrece una inmersión cultural intensa.",
    'destination_kyoto': 'Kioto, Japón',
    'destination_kyoto_desc': "Ex capitale imperiale, Kyoto incarna l'anima tradizionale del Giappone con i suoi templi zen, giardini giapponesi, santuari shintoisti e case di geishas. Un'immersione nella serenità ed estetica giapponese.",
    'destination_santorini': 'Santorini, Grecia',
    'destination_santorini_desc': 'Questa isola delle Cicladi offre paesaggi mozzafiato con le sue case bianche con cupole blu che si affacciano sul mar Egeo. Goditi tramonti spettacolari, spiagge vulcaniche e gastronomia greca.',
    'best_time_to_visit': 'Periodo migliore per visitare',
    'highlights': 'Destacados',
    // ---- Landing page (lp_*) ----
    'lp_navCta': 'Empezar',
    'lp_navPlan': 'Planificar un viaje',
    'lp_badge': 'Nuevo · Agente de viajes con IA',
    'lp_heroTitle': 'Cuéntanos tu viaje.',
    'lp_heroTitleHighlight': 'Nosotros hacemos el resto.',
    'lp_heroSubtitle': 'Nuestra IA crea tu itinerario día a día, compara vuelos y hoteles en tiempo real y lo reserva todo al mejor precio. En menos de un minuto.',
    'lp_heroCta': 'Crear mi viaje',
    'lp_heroCtaSecondary': 'Ver cómo funciona',
    'lp_fieldWhere': 'Destino',
    'lp_fieldDeparture': 'Ida',
    'lp_fieldReturn': 'Vuelta',
    'lp_socialProof': 'Más de 12 000 viajeros satisfechos',
    'lp_rating': '4,9/5 de satisfacción',
    'lp_mockUser': 'Una semana en Lisboa en octubre, 1200 € para dos, sobre todo gastronomía y cultura.',
    'lp_mockStep1': 'Buscando vuelos París → Lisboa',
    'lp_mockStep2': 'Comparando 128 hoteles disponibles',
    'lp_mockStep3': 'Construyendo el itinerario de 7 días',
    'lp_mockAgent': 'Aquí tienes tu viaje: 7 días en Lisboa con Alfama, Belém, un día en Sintra y 5 mesas reservadas. Total 1042 €, 158 € por debajo de tu presupuesto.',
    'lp_mockFlightTag': 'Vuelo ida y vuelta',
    'lp_mockFlightTitle': 'París CDG → Lisboa',
    'lp_mockFlightSub': '2 h 45 · directo · 12 oct.',
    'lp_mockHotelTag': 'Hotel',
    'lp_mockHotelTitle': 'Baixa Boutique Hotel',
    'lp_mockHotelSub': '4★ · centro histórico · desayuno incluido',
    'lp_mockBudget': 'Presupuesto total',
    'lp_mockFloatingTag': 'Itinerario',
    'lp_mockFloatingValue': '7 días planificados',
    'lp_mockFloating2Tag': 'Ahorro',
    'lp_mockFloating2Value': '158 € por debajo',
    'lp_statsTitle': 'Conectado a las mejores fuentes de viaje',
    'lp_stat1': 'aerolíneas conectadas',
    'lp_stat2': 'hoteles y alojamientos comparados',
    'lp_stat3': 'para un itinerario completo',
    'lp_stat4': 'valoración media de los viajeros',
    'lp_stepsTag': 'Cómo funciona',
    'lp_stepsTitle': 'Tres pasos. Cero complicaciones.',
    'lp_stepsSubtitle': 'Se acabaron las pestañas acumuladas y las hojas de cálculo. Tú describes, nosotros organizamos.',
    'lp_step1Title': 'Describe lo que quieres',
    'lp_step1Desc': 'En una frase: destino, fechas, presupuesto, ambiente. Como si hablaras con un amigo que conoce el mundo entero.',
    'lp_step2Title': 'La IA compone tu viaje',
    'lp_step2Desc': 'Busca vuelos, compara hoteles, selecciona actividades y monta un itinerario coherente, hora a hora.',
    'lp_step3Title': 'Reserva en un clic',
    'lp_step3Desc': 'Todo llega a tu carrito. Un único pago seguro y tus confirmaciones te esperan en tu cuenta.',
    'lp_featuresTag': 'Funcionalidades',
    'lp_featuresTitle': 'Un copiloto de viaje, no un buscador',
    'lp_featuresSubtitle': 'Todo lo necesario para pasar de la idea al embarque, reunido en un solo lugar.',
    'lp_feat1Title': 'Un itinerario día a día realmente pensado para ti',
    'lp_feat1Desc': 'Cada jornada está equilibrada: tiempos de trayecto, horarios de apertura, pausas para comer. Modificable en cualquier momento con un simple mensaje.',
    'lp_feat1Day1': 'Día 1 · Alfama y miradores',
    'lp_feat1Day1Detail': 'Tranvía 28, castillo de San Jorge, cena con fado',
    'lp_feat1Day2': 'Día 2 · Belém',
    'lp_feat1Day2Detail': 'Monasterio de los Jerónimos, pastéis de Belém',
    'lp_feat1Day3': 'Día 3 · Sintra',
    'lp_feat1Day3Detail': 'Palacio da Pena, Quinta da Regaleira',
    'lp_feat2Title': 'Vuelos en tiempo real',
    'lp_feat2Desc': 'Precios y disponibilidad en directo de cientos de aerolíneas, sin abrir otra pestaña.',
    'lp_feat3Title': 'Hoteles y sitios seleccionados',
    'lp_feat3Desc': 'Alojamientos elegidos según tu presupuesto y tu barrio ideal, con opiniones incluidas.',
    'lp_feat4Title': 'Pago seguro',
    'lp_feat4Desc': 'Vuelos, hoteles y actividades en un solo carrito, pagados de una vez con Stripe.',
    'lp_feat5Title': 'Presupuesto bajo control',
    'lp_feat5Desc': 'El total se actualiza en directo: siempre sabes dónde estás antes de confirmar.',
    'lp_feat6Title': 'Disponible en 5 idiomas',
    'lp_feat6Desc': 'ItinaryMe habla tu idioma y se adapta automáticamente a tu país y a tu moneda.',
    'lp_destTag': 'Inspiración',
    'lp_destTitle': '¿A dónde viajas este año?',
    'lp_destSubtitle': 'Elige un destino y la IA construye el viaje completo en segundos.',
    'lp_destCta': 'Todos los destinos',
    'lp_testiTag': 'Testimonios',
    'lp_testiTitle': 'Dejaron que la IA planificara',
    'lp_testi1': 'Describí mi viaje en dos frases y recibí un itinerario de 10 días por Japón mejor armado que el que preparé en tres fines de semana.',
    'lp_testi1Name': 'Camille L.',
    'lp_testi1Role': 'Viaje a Japón, 10 días',
    'lp_testi2': 'El comparador de vuelos integrado me ahorró 240 € en billetes. Y nunca salí de la aplicación para reservar.',
    'lp_testi2Name': 'Marc R.',
    'lp_testi2Role': 'Fin de semana en Barcelona',
    'lp_testi3': 'Viajar cuatro personas con dos niños era un rompecabezas. Esta vez todo encajaba: horarios, distancias, restaurantes adecuados.',
    'lp_testi3Name': 'Amélie D.',
    'lp_testi3Role': 'Vacaciones en familia en Portugal',
    'lp_ctaTitle': 'Tu próximo viaje empieza ahora',
    'lp_ctaSubtitle': 'Crea tu primer itinerario gratis. Solo pagas lo que reservas.',
    'lp_ctaButton': 'Crear mi itinerario',
    'lp_ctaSecondary': 'Ver la demo',
    'lp_ctaPerk1': 'Sin tarjeta de crédito',
    'lp_ctaPerk2': 'Itinerario listo en 60 segundos',
    'lp_ctaPerk3': 'Cancelación según las condiciones del proveedor',
    // Footer translations
    'footer_about': 'Acerca de',
    'footer_ourStory': 'Nuestra Historia',
    'footer_howItWorks': 'Cómo Funciona',
    'footer_testimonials': 'Testimonios',
    'footer_destinations': 'Destinos',
    'footer_popular': 'Populares',
    'footer_bySeason': 'Por Temporada',
    'footer_allDestinations': 'Todos los Destinos',
    'footer_contact': 'Contacto',
    'footer_contactUs': 'Contáctenos',
    'footer_support': 'Soporte',
    'footer_faq': 'Preguntas Frecuentes',
    'footer_copyright': '© 2025 ItinaryMe. Todos los derechos reservados.',
    'footer_privacy': 'Política de Privacidad',
    'footer_terms': 'Términos de Servicio',
    'footer_cookies': 'Cookies',
    'footer_tagline': 'Su socio de confianza para planificar viajes inolvidables y personalizados.',
  },
  de: {
    'home': 'Startseite',
    'destinations': 'Reiseziele',
    'about': 'Über uns',
    'contact': 'Kontakt',
    'login': 'Anmelden',
    'logout': 'Abmelden',
    'search': 'Suchen',
    'personalizedTrip': 'Ihre personalisierte Reise, für Sie entworfen',
    'personalizedTripDescription': 'Maßgeschneiderte Reiserouten, die Ihren Interessen, Vorlieben und Reisestil entsprechen.',
    'whereDoYouWantToGo': 'Wohin möchten Sie reisen?',
    'date': 'Wann?',
    'howLong': 'Wie lange?',
    'getStarted': 'Loslegen',
    'customizedItineraries': 'Maßgeschneiderte Reisepläne',
    'customizedItinerariesDescription': 'Erhalten Sie einen detaillierten Reiseplan, der auf Ihre Interessen und Vorlieben zugeschnitten ist.',
    'expertPlanning': 'Expertenplanung',
    'expertPlanningDescription': 'Unsere Reisespezialisten nutzen ihr Wissen, um Ihre perfekte Reise zu gestalten.',
    'seamlessExperience': 'Nahtloses Erlebnis',
    'seamlessExperienceDescription': 'Genießen Sie eine sorgenfreie Reise mit Buchungen und Details, die für Sie arrangiert werden.',
    'footerText': '© 2025 ItinaryMe. Alle Rechte vorbehalten.',
    'dashboard': 'Dashboard',
    'guests': 'Gäste',
    'myTrips': 'Meine Reisen',
    'howItWorks': 'Wie es funktioniert',
    'aboutUs': 'Über Uns',
    'popularDestinations': 'Beliebte Reiseziele',
    // Contact page translations
    'contactUs': 'Kontaktieren Sie uns',
    'contactDescription': 'Haben Sie Fragen oder Anregungen? Zögern Sie nicht, uns zu kontaktieren.',
    'fullName': 'Vollständiger Name',
    'email': 'E-Mail',
    'message': 'Nachricht',
    'sendMessage': 'Nachricht senden',
    'sending': 'Wird gesendet...',
    'messageSent': 'Nachricht gesendet!',
    'thankYouMessage': 'Vielen Dank für Ihre Nachricht. Wir werden uns in Kürze bei Ihnen melden.',
    'sendAnotherMessage': 'Eine weitere Nachricht senden',
    'fillAllFields': 'Bitte füllen Sie alle Felder aus.',
    'errorOccurred': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.',
    'contactInfo': 'Kontaktinformationen',
    'phone': 'Telefon',
    'address': 'Adresse',
    'openingHours': 'Öffnungszeiten',
    'mondayFriday': 'Montag - Freitag',
    'saturday': 'Samstag',
    'sunday': 'Sonntag',
    'closed': 'Geschlossen',
    // How it works page translations
    'howItWorksDescription': 'Entdecken Sie, wie ItinaryMe die Art und Weise revolutioniert, wie Sie Ihre Reisen planen, in nur wenigen einfachen Schritten.',
    'sharePreferences': 'Teilen Sie Ihre Vorlieben',
    'sharePreferencesDescription': 'Sagen Sie uns, wohin Sie reisen möchten, wann und was Sie mögen. Je mehr Informationen Sie uns geben, desto besser können wir Ihr Erlebnis personalisieren.',
    'aiCreatesItinerary': 'Unsere KI erstellt Ihre Reiseroute',
    'aiCreatesItineraryDescription': 'Unsere fortschrittliche künstliche Intelligenz erstellt eine tägliche Reiseroute, die auf Ihre Vorlieben, Ihr Budget und Ihre verfügbare Zeit zugeschnitten ist.',
    'customizeAndTravel': 'Anpassen und Reisen',
    'customizeAndTravelDescription': 'Verfeinern Sie Ihre Reiseroute, bis sie perfekt ist, und nehmen Sie sie mit. Greifen Sie jederzeit auf Ihre Pläne zu, auch offline während Ihrer Reise.',
    'features': 'Unsere Funktionen',
    'customizedItinerariesFeature': 'Maßgeschneiderte Reiserouten',
    'customizedItinerariesFeatureDescription': 'Reisepläne, die auf Ihre Interessen zugeschnitten sind, keine generischen Reiserouten. Entdecken Sie Sehenswürdigkeiten und versteckte Juwelen.',
    'quickPlanning': 'Schnelle Planung',
    'quickPlanningDescription': 'Erhalten Sie eine vollständige Reiseroute in Minuten, nicht in Stunden. Unsere KI erledigt die schwere Arbeit für Sie.',
    'budgetOptions': 'Budgetfreundliche Optionen',
    'budgetOptionsDescription': 'Vorschläge, die Ihr Budget respektieren, sei es knapp oder großzügig. Machen Sie das Beste aus jedem ausgegebenen Euro.',
    'mapsDirections': 'Karten und Wegbeschreibungen',
    'mapsDirectionsDescription': 'Integrierte interaktive Karten und Navigationsanweisungen, die Ihnen helfen, sich an unbekannten Orten stressfrei zu bewegen.',
    'readyToPlan': 'Bereit, Ihr Abenteuer zu planen?',
    'startTodayDescription': 'Beginnen Sie noch heute und entdecken Sie, wie einfach und angenehm Reiseplanung sein kann.',
    'planMyTrip': 'Meine Reise planen',
    // About page translations
    'aboutDescription': 'Entdecken Sie, wie wir die Art und Weise verändern, wie Sie Ihre Reisen planen',
    'ourMission': 'Unsere Mission',
    'ourMissionDescription1': 'Bei ItinaryMe ist es unsere Mission, die Reiseplanung zu vereinfachen, indem wir eine intuitive Plattform anbieten, die Technologie und menschliches Fachwissen kombiniert.',
    'ourMissionDescription2': 'Wir glauben, dass jede Reise ein einzigartiges Erlebnis sein sollte, das auf Ihre persönlichen Vorlieben zugeschnitten ist und frei von den üblichen Planungsschwierigkeiten.',
    'ourHistory': 'Unsere Geschichte',
    'ourHistoryDescription1': 'ItinaryMe entstand 2025 aus der Frustrazione seiner Gründer über die Komplexität, unvergessliche Reisen zu planen, ohne stundenlang daran zu arbeiten.',
    'ourHistoryDescription2': 'Seitdem haben wir Tausenden von Reisenden geholfen, personalisierte Reiserouten zu erstellen, die perfekt zu ihren Wünschen und ihrem Budget passen.',
    'howItFunctions': 'Wie es funktioniert',
    'shareYourPreferences': 'Teilen Sie Ihre Vorlieben',
    'shareYourPreferencesDescription': 'Teilen Sie uns Ihr Reiseziel, Reisedaten und Ihre Interessen mit.',
    'personalizedAIAssistant': 'Personalisierter KI-Assistent',
    'personalizedAIAssistantDescription': 'Il nostro assistente intelligente creerà un itinerario adatto alle tue preferenze.',
    'enjoyYourTrip': 'Genießen Sie Ihre Reise',
    'enjoyYourTripDescription': 'Greifen Sie jederzeit auf Ihre detaillierte Reiseroute zu und ändern Sie sie.',
    'readyToPlanYourNextTrip': 'Bereit, Ihre nächste Reise zu planen?',
    'joinThousandsOfTravelers': 'Schließen Sie sich Tausenden von Reisenden an, die ihre Planung mit ItinaryMe bereits vereinfacht haben.',
    'startYourItinerary': 'Starten Sie Ihre Reiseroute',
    // Destinations page translations
    'destinationsDescription': 'Entdecken Sie Traumziele aus der ganzen Welt und beginnen Sie mit der Planung Ihrer nächsten Reise',
    'searchDestination': 'Nach einem Reiseziel suchen...',
    'filterBySeason': 'Nach Jahreszeit filtern:',
    'allSeasons': 'Alle Jahreszeiten',
    'spring': 'Frühling',
    'summer': 'Sommer',
    'autumn': 'Herbst',
    'winter': 'Winter',
    'noDestinationsFound': 'Keine Reiseziele entsprechen Ihren Kriterien. Bitte versuchen Sie eine andere Suche.',
    'cantFindDreamDestination': 'Können Sie Ihr Traumziel nicht finden? Kontaktieren Sie uns und wir helfen Ihnen bei der Planung.',
    // Destinations translations
    'destination_paris': 'Paris, Frankreich',
    'destination_paris_desc': "Die Stadt der Liebe, Paris ist gefüllt mit ikonischen Wahrzeichen wie dem Eiffelturm, dem Louvre und Notre Dame. Entdecken Sie die Kunst, Küche und einzigartige Architektur dieser europäischen Hauptstadt.",
    'destination_tokyo': 'Tokio, Japan',
    'destination_tokyo_desc': "Eine faszinierende Mischung aus alten Traditionen und futuristischer Technologie, Tokio ist eine pulsierende Metropole, die ein einzigartiges kulturelles Erlebnis, raffinierte Küche und Viertel mit kontrastierenden Atmosphären bietet.",
    'destination_new_york': 'New York, Vereinigte Staaten',
    'destination_new_york_desc': 'Die Stadt, die niemals schläft, bietet unvergleichliche Energie, ikonische Wolkenkratzer, Weltklasse-Museen, eine dynamische Kulturszene und vielfältige Viertel zum Erkunden.',
    'destination_rome': 'Rom, Italien',
    'destination_rome_desc': "Die Ewige Stadt ist ein Freilichtmuseum, in dem die antike Geschichte auf das moderne Leben trifft. Entdecken Sie die Überreste des Römischen Reiches, authentische italienische Küche und die einzigartige Atmosphäre von Plätzen und Brunnen.",
    'destination_bali': 'Bali, Indonesien',
    'destination_bali_desc': "Die Insel der Götter bietet paradiesische Strände, terrassierte Reisfelder, spirituelle Tempel und eine reiche Kultur. Bali ist ideal zum Entspannen, Yoga oder Abenteuer.",
    'destination_barcelona': 'Barcelona, Spanien',
    'destination_barcelona_desc': 'Mit seiner einzigartigen Gaudí-Architektur, städtischen Stränden, katalanischen Küche und festlichen Atmosphäre ist Barcelona ein perfektes mediterranes Ziel für einen kulturellen Städtetrip.',
    'destination_marrakech': 'Marrakesch, Marokko',
    'destination_marrakech_desc': "Die rote Stadt taucht Sie in die Farben und Düfte Nordafrikas ein. Zwischen lebhaften Souks, majestätischen Palästen und üppigen Gärten bietet Marrakesch ein intensives kulturelles Erlebnis.",
    'destination_kyoto': 'Kyoto, Japan',
    'destination_kyoto_desc': "Als ehemalige kaiserliche Hauptstadt verkörpert Kyoto die traditionelle Seele Japans mit seinen Zen-Tempeln, japanischen Gärten, Shinto-Schreinen und Geisha-Häusern. Ein Eintauchen in japanische Gelassenheit und Ästhetik.",
    'destination_santorini': 'Santorini, Griechenland',
    'destination_santorini_desc': 'Diese Kykladeninsel bietet atemberaubende Landschaften mit ihren weißen Häusern mit blauen Kuppeln mit Blick auf die Ägäis. Genießen Sie spektakuläre Sonnenuntergänge, vulkanische Strände und griechische Gastronomie.',
    'best_time_to_visit': 'Beste Reisezeit',
    'highlights': 'Highlights',
    // ---- Landing page (lp_*) ----
    'lp_navCta': 'Loslegen',
    'lp_navPlan': 'Reise planen',
    'lp_badge': 'Neu · KI-Reiseagent',
    'lp_heroTitle': 'Erzählen Sie uns Ihre Reise.',
    'lp_heroTitleHighlight': 'Den Rest übernehmen wir.',
    'lp_heroSubtitle': 'Unsere KI erstellt Ihren Reiseplan Tag für Tag, vergleicht Flüge und Hotels in Echtzeit und bucht alles zum besten Preis. In weniger als einer Minute.',
    'lp_heroCta': 'Reise erstellen',
    'lp_heroCtaSecondary': 'So funktioniert es',
    'lp_fieldWhere': 'Reiseziel',
    'lp_fieldDeparture': 'Hinreise',
    'lp_fieldReturn': 'Rückreise',
    'lp_socialProof': 'Über 12.000 begeisterte Reisende',
    'lp_rating': '4,9/5 Zufriedenheit',
    'lp_mockUser': 'Eine Woche Lissabon im Oktober, 1.200 € zu zweit, vor allem Essen und Kultur.',
    'lp_mockStep1': 'Suche Flüge Paris → Lissabon',
    'lp_mockStep2': 'Vergleich von 128 verfügbaren Hotels',
    'lp_mockStep3': 'Erstellung des 7-Tage-Reiseplans',
    'lp_mockAgent': 'Hier ist Ihre Reise: 7 Tage Lissabon mit Alfama, Belém, einem Tag in Sintra und 5 reservierten Tischen. Gesamt 1.042 € – 158 € unter Ihrem Budget.',
    'lp_mockFlightTag': 'Hin- und Rückflug',
    'lp_mockFlightTitle': 'Paris CDG → Lissabon',
    'lp_mockFlightSub': '2 Std. 45 · direkt · 12. Okt.',
    'lp_mockHotelTag': 'Hotel',
    'lp_mockHotelTitle': 'Baixa Boutique Hotel',
    'lp_mockHotelSub': '4★ · Altstadt · Frühstück inklusive',
    'lp_mockBudget': 'Gesamtbudget',
    'lp_mockFloatingTag': 'Reiseplan',
    'lp_mockFloatingValue': '7 Tage geplant',
    'lp_mockFloating2Tag': 'Ersparnis',
    'lp_mockFloating2Value': '158 € unter Budget',
    'lp_statsTitle': 'Verbunden mit den besten Reisequellen',
    'lp_stat1': 'angebundene Fluggesellschaften',
    'lp_stat2': 'verglichene Hotels und Unterkünfte',
    'lp_stat3': 'für einen vollständigen Reiseplan',
    'lp_stat4': 'durchschnittliche Bewertung',
    'lp_stepsTag': 'Wie es funktioniert',
    'lp_stepsTitle': 'Drei Schritte. Null Aufwand.',
    'lp_stepsSubtitle': 'Keine Tab-Sammlungen mehr, keine Tabellen. Sie beschreiben, wir organisieren.',
    'lp_step1Title': 'Beschreiben Sie Ihre Wünsche',
    'lp_step1Desc': 'In einem Satz: Ziel, Daten, Budget, Stimmung. Als würden Sie mit einer Freundin oder einem Freund sprechen, die oder der die ganze Welt kennt.',
    'lp_step2Title': 'Die KI stellt Ihre Reise zusammen',
    'lp_step2Desc': 'Sie sucht Flüge, vergleicht Hotels, wählt Aktivitäten aus und baut daraus einen stimmigen Plan – Stunde für Stunde.',
    'lp_step3Title': 'Mit einem Klick buchen',
    'lp_step3Desc': 'Alles landet im Warenkorb. Eine sichere Zahlung, und Ihre Bestätigungen warten in Ihrem Konto.',
    'lp_featuresTag': 'Funktionen',
    'lp_featuresTitle': 'Ein Reise-Copilot, keine Suchmaschine',
    'lp_featuresSubtitle': 'Alles, was Sie brauchen – von der ersten Idee bis zum Boarding, an einem Ort.',
    'lp_feat1Title': 'Ein Reiseplan Tag für Tag, wirklich für Sie gemacht',
    'lp_feat1Desc': 'Jeder Tag ist ausbalanciert: Fahrzeiten, Öffnungszeiten, Mittagspausen. Jederzeit mit einer kurzen Nachricht änderbar.',
    'lp_feat1Day1': 'Tag 1 · Alfama & Aussichtspunkte',
    'lp_feat1Day1Detail': 'Tram 28, Burg São Jorge, Fado-Abendessen',
    'lp_feat1Day2': 'Tag 2 · Belém',
    'lp_feat1Day2Detail': 'Hieronymuskloster, Pastéis de Belém',
    'lp_feat1Day3': 'Tag 3 · Sintra',
    'lp_feat1Day3Detail': 'Palácio da Pena, Quinta da Regaleira',
    'lp_feat2Title': 'Flüge in Echtzeit',
    'lp_feat2Desc': 'Live-Preise und Verfügbarkeiten von Hunderten Airlines – ohne einen weiteren Tab.',
    'lp_feat3Title': 'Kuratierte Hotels und Adressen',
    'lp_feat3Desc': 'Unterkünfte passend zu Ihrem Budget und Ihrem Wunschviertel, inklusive Bewertungen.',
    'lp_feat4Title': 'Sichere Zahlung',
    'lp_feat4Desc': 'Flüge, Hotels und Aktivitäten in einem Warenkorb, in einem Schritt über Stripe bezahlt.',
    'lp_feat5Title': 'Budget im Griff',
    'lp_feat5Desc': 'Die Summe aktualisiert sich live: Sie wissen vor dem Bestätigen immer, wo Sie stehen.',
    'lp_feat6Title': 'In 5 Sprachen verfügbar',
    'lp_feat6Desc': 'ItinaryMe spricht Ihre Sprache und passt sich automatisch an Ihr Land und Ihre Währung an.',
    'lp_destTag': 'Inspiration',
    'lp_destTitle': 'Wohin geht es dieses Jahr?',
    'lp_destSubtitle': 'Wählen Sie ein Ziel – die KI baut die komplette Reise in Sekunden.',
    'lp_destCta': 'Alle Reiseziele',
    'lp_testiTag': 'Erfahrungsberichte',
    'lp_testiTitle': 'Sie haben die KI planen lassen',
    'lp_testi1': 'Ich habe meine Reise in zwei Sätzen beschrieben und einen 10-Tage-Plan für Japan bekommen, der besser war als der, an dem ich drei Wochenenden gesessen habe.',
    'lp_testi1Name': 'Camille L.',
    'lp_testi1Role': 'Japanreise, 10 Tage',
    'lp_testi2': 'Der integrierte Flugvergleich hat mir 240 € gespart. Und ich musste die App zum Buchen nie verlassen.',
    'lp_testi2Name': 'Marc R.',
    'lp_testi2Role': 'Wochenende in Barcelona',
    'lp_testi3': 'Zu viert mit zwei Kindern zu reisen war immer ein Puzzle. Diesmal passte alles: Zeiten, Entfernungen, kinderfreundliche Restaurants.',
    'lp_testi3Name': 'Amélie D.',
    'lp_testi3Role': 'Familienurlaub in Portugal',
    'lp_ctaTitle': 'Ihre nächste Reise beginnt jetzt',
    'lp_ctaSubtitle': 'Erstellen Sie Ihren ersten Reiseplan kostenlos. Sie zahlen nur, was Sie buchen.',
    'lp_ctaButton': 'Reiseplan erstellen',
    'lp_ctaSecondary': 'Demo ansehen',
    'lp_ctaPerk1': 'Ohne Kreditkarte',
    'lp_ctaPerk2': 'Reiseplan in 60 Sekunden',
    'lp_ctaPerk3': 'Stornierung nach den Bedingungen des Anbieters',
    // Footer translations
    'footer_about': 'Über uns',
    'footer_ourStory': 'Unsere Geschichte',
    'footer_howItWorks': 'Wie es funktioniert',
    'footer_testimonials': 'Erfahrungsberichte',
    'footer_destinations': 'Reiseziele',
    'footer_popular': 'Beliebt',
    'footer_bySeason': 'Nach Jahreszeit',
    'footer_allDestinations': 'Alle Reiseziele',
    'footer_contact': 'Kontakt',
    'footer_contactUs': 'Kontaktieren Sie uns',
    'footer_support': 'Support',
    'footer_faq': 'Häufige Fragen',
    'footer_copyright': '© 2025 ItinaryMe. Alle Rechte vorbehalten.',
    'footer_privacy': 'Datenschutz',
    'footer_terms': 'Nutzungsbedingungen',
    'footer_cookies': 'Cookies',
    'footer_tagline': 'Ihr vertrauenswürdiger Partner für die Planung unvergesslicher, personalisierter Reisen.',
  },
  it: {
    'home': 'Home',
    'destinations': 'Destinazioni',
    'about': 'Chi siamo',
    'contact': 'Contatti',
    'login': 'Accedi',
    'logout': 'Esci',
    'search': 'Cerca',
    'personalizedTrip': 'Il tuo viaggio personalizzato, progettato per te',
    'personalizedTripDescription': 'Itinerari su misura per soddisfare i tuoi interessi, preferenze e stile di viaggio.',
    'whereDoYouWantToGo': 'Dove vuoi andare?',
    'date': 'Quando?',
    'howLong': 'Per quanto tempo?',
    'getStarted': 'Iniziare',
    'customizedItineraries': 'Itinerari personalizzati',
    'customizedItinerariesDescription': 'Ricevi un itinerario dettagliato in base ai tuoi interessi e preferenze.',
    'expertPlanning': 'Pianificazione esperta',
    'expertPlanningDescription': 'I nostri specialisti di viaggio utilizzano le loro conoscenze per creare il tuo viaggio perfetto.',
    'seamlessExperience': 'Esperienza senza intoppi',
    'seamlessExperienceDescription': 'Goditi un viaggio senza stress con prenotazioni e dettagli organizzati per te.',
    'footerText': '© 2025 ItinaryMe. Tutti i diritti riservati.',
    'dashboard': 'Dashboard',
    'guests': 'Ospiti',
    'myTrips': 'I miei viaggi',
    'howItWorks': 'Come funziona',
    'aboutUs': 'Chi Siamo',
    'popularDestinations': 'Destinazioni Popolari',
    // Contact page translations
    'contactUs': 'Contattaci',
    'contactDescription': 'Hai domande o suggerimenti? Non esitare a contattarci.',
    'fullName': 'Nome completo',
    'email': 'Email',
    'message': 'Messaggio',
    'sendMessage': 'Invia messaggio',
    'sending': 'Invio in corso...',
    'messageSent': 'Messaggio inviato!',
    'thankYouMessage': 'Grazie per averci contattato. Ti risponderemo al più presto.',
    'sendAnotherMessage': 'Invia un altro messaggio',
    'fillAllFields': 'Si prega di compilare tutti i campi.',
    'errorOccurred': 'Si è verificato un errore. Per favore riprova più tardi.',
    'contactInfo': 'Informazioni di contatto',
    'phone': 'Telefono',
    'address': 'Indirizzo',
    'openingHours': 'Orari di apertura',
    'mondayFriday': 'Lunedì - Venerdì',
    'saturday': 'Sabato',
    'sunday': 'Domenica',
    'closed': 'Chiuso',
    // How it works page translations
    'howItWorksDescription': 'Scopri come ItinaryMe rivoluziona il modo in cui pianifichi i tuoi viaggi, in pochi semplici passaggi.',
    'sharePreferences': 'Condividi le tue preferenze',
    'sharePreferencesDescription': 'Dicci dove vuoi andare, quando e cosa ti piace. Più informazioni ci fornisci, più possiamo personalizzare la tua esperienza.',
    'aiCreatesItinerary': 'La nostra IA crea il tuo itinerario',
    'aiCreatesItineraryDescription': 'La nostra intelligenza artificiale avanzata crea un itinerario giorno per giorno, su misura per le tue preferenze, il tuo budget e il tempo a disposizione.',
    'customizeAndTravel': 'Personalizza e viaggia',
    'customizeAndTravelDescription': 'Perfeziona il tuo itinerario fino a quando non è perfetto, poi portalo con te. Accedi ai tuoi piani in qualsiasi momento, anche offline durante il viaggio.',
    'features': 'Le nostre caratteristiche',
    'customizedItinerariesFeature': 'Itinerari personalizzati',
    'customizedItinerariesFeatureDescription': 'Piani di viaggio adattati ai tuoi interessi, non itinerari generici. Scopri luoghi imperdibili e gemme nascoste.',
    'quickPlanning': 'Pianificazione rapida',
    'quickPlanningDescription': 'Ottieni un itinerario completo in minuti, non in ore. La nostra IA fa il lavoro duro per te.',
    'budgetOptions': 'Opzioni adatte al budget',
    'budgetOptionsDescription': 'Suggerimenti che rispettano il tuo budget, che sia limitato o generoso. Sfrutta al massimo ogni euro speso.',
    'mapsDirections': 'Mappe e indicazioni',
    'mapsDirectionsDescription': 'Mappe interattive integrate e istruzioni di navigazione per aiutarti a muoverti senza stress in luoghi sconosciuti.',
    'readyToPlan': 'Pronto a pianificare la tua avventura?',
    'startTodayDescription': 'Inizia oggi e scopri quanto può essere facile e piacevole la pianificazione del viaggio.',
    'planMyTrip': 'Pianifica il mio viaggio',
    // About page translations
    'aboutDescription': 'Scopri come trasformiamo il modo in cui pianifichi i tuoi viaggi',
    'ourMission': 'La Nostra Missione',
    'ourMissionDescription1': 'In ItinaryMe, la nostra missione è semplificare la pianificazione dei viaggi offrendo una piattaforma intuitiva che combina tecnologia ed esperienza umana.',
    'ourMissionDescription2': 'Crediamo che ogni viaggio dovrebbe essere un\'esperienza unica, adattata alle tue preferenze personali e priva dei soliti problemi di pianificazione.',
    'ourHistory': 'La Nostra Storia',
    'ourHistoryDescription1': 'ItinaryMe è nato nel 2025 dalla frustrazione dei suoi fondatori per la complessità di pianificare viaggi memorabili senza passarci ore.',
    'ourHistoryDescription2': 'Da allora, abbiamo aiutato migliaia di viaggiatori a creare itinerari personalizzati che corrispondono perfettamente ai loro desideri e al loro budget.',
    'howItFunctions': 'Come Funziona',
    'shareYourPreferences': 'Condividi le Tue Preferenze',
    'shareYourPreferencesDescription': 'Indicaci la tua destinazione, le date di viaggio e i tuoi interessi.',
    'personalizedAIAssistant': 'Assistente IA Personalizzato',
    'personalizedAIAssistantDescription': 'Nuestro assistente intelligente creerà un itinerario adatto alle tue preferenze.',
    'enjoyYourTrip': 'Goditi il Tuo Viaggio',
    'enjoyYourTripDescription': 'Accedi al tuo itinerario dettagliato e modificalo in qualsiasi momento.',
    'readyToPlanYourNextTrip': 'Pronto a pianificare il tuo prossimo viaggio?',
    'joinThousandsOfTravelers': 'Unisciti a migliaia di viaggiatori che hanno già semplificato la loro pianificazione con ItinaryMe.',
    'startYourItinerary': 'Inizia il Tuo Itinerario',
    // Destinations page translations
    'destinationsDescription': 'Scopri destinazioni da sogno da tutto il mondo e inizia a pianificare il tuo prossimo viaggio',
    'searchDestination': 'Cerca una destinazione...',
    'filterBySeason': 'Filtra per stagione:',
    'allSeasons': 'Tutte le stagioni',
    'spring': 'Primavera',
    'summer': 'Estate',
    'autumn': 'Autunno',
    'winter': 'Inverno',
    'noDestinationsFound': 'Nessuna destinazione corrisponde ai tuoi criteri. Prova un\'altra ricerca.',
    'cantFindDreamDestination': 'Non riesci a trovare la tua destinazione da sogno? Contattaci e ti aiuteremo a pianificarla.',
    // Destinations translations
    'destination_paris': 'Parigi, Francia',
    'destination_paris_desc': "La città dell'amore, Parigi è piena di luoghi iconici come la Torre Eiffel, il Louvre e Notre Dame. Scopri l'arte, la cucina e l'architettura unica di questa capitale europea.",
    'destination_tokyo': 'Tokyo, Giappone',
    'destination_tokyo_desc': "Un affascinante mix di antiche tradizioni e tecnologia futuristica, Tokyo è una metropoli vibrante che offre un'esperienza culturale unica, una cucina raffinata e quartieri con atmosfere contrastanti.",
    'destination_new_york': 'New York, Stati Uniti',
    'destination_new_york_desc': "La città che non dorme mai offre un'energia senza pari, grattacieli iconici, musei di livello mondiale, una scena culturale dinamica e quartieri diversificati da esplorare.",
    'destination_rome': 'Roma, Italia',
    'destination_rome_desc': "La Città Eterna è un museo a cielo aperto dove la storia antica incontra la vita moderna. Scopri i resti dell'Impero Romano, l'autentica cucina italiana e l'atmosfera unica di piazze e fontane.",
    'destination_bali': 'Bali, Indonesia',
    'destination_bali_desc': "L'isola degli dei offre spiagge paradisiache, risaie a terrazza, templi spirituali e una ricca cultura. Bali è ideale per rilassarsi, praticare yoga o avventurarsi.",
    'destination_barcelona': 'Barcellona, Spagna',
    'destination_barcelona_desc': "Con la sua architettura unica di Gaudí, le spiagge urbane, la cucina catalana e l'atmosfera festosa, Barcellona è una destinazione mediterranea perfetta per una fuga culturale.",
    'destination_marrakech': 'Marrakech, Marocco',
    'destination_marrakech_desc': "La città rossa ti immerge nei colori e nei profumi del Nord Africa. Tra vivaci souk, maestosi palazzi e rigogliosi giardini, Marrakech offre un'intensa immersione culturale.",
    'destination_kyoto': 'Kyoto, Giappone',
    'destination_kyoto_desc': "Ex capitale imperiale, Kyoto incarna l'anima tradizionale del Giappone con i suoi templi zen, giardini giapponesi, santuari shintoisti e case di geishas. Un'immersione nella serenità ed estetica giapponese.",
    'destination_santorini': 'Santorini, Grecia',
    'destination_santorini_desc': 'Questa isola delle Cicladi offre paesaggi mozzafiato con le sue case bianche con cupole blu che si affacciano sul mar Egeo. Goditi tramonti spettacolari, spiagge vulcaniche e gastronomia greca.',
    'best_time_to_visit': 'Periodo migliore per visitare',
    'highlights': 'Punti salienti',
    // ---- Landing page (lp_*) ----
    'lp_navCta': 'Inizia',
    'lp_navPlan': 'Pianifica un viaggio',
    'lp_badge': 'Novità · Agente di viaggio IA',
    'lp_heroTitle': 'Raccontaci il tuo viaggio.',
    'lp_heroTitleHighlight': 'Al resto pensiamo noi.',
    'lp_heroSubtitle': "La nostra IA crea il tuo itinerario giorno per giorno, confronta voli e hotel in tempo reale e prenota tutto al miglior prezzo. In meno di un minuto.",
    'lp_heroCta': 'Crea il mio viaggio',
    'lp_heroCtaSecondary': 'Scopri come funziona',
    'lp_fieldWhere': 'Destinazione',
    'lp_fieldDeparture': 'Andata',
    'lp_fieldReturn': 'Ritorno',
    'lp_socialProof': 'Oltre 12.000 viaggiatori soddisfatti',
    'lp_rating': '4,9/5 di soddisfazione',
    'lp_mockUser': 'Una settimana a Lisbona a ottobre, 1.200 € in due, soprattutto cibo e cultura.',
    'lp_mockStep1': 'Ricerca voli Parigi → Lisbona',
    'lp_mockStep2': 'Confronto di 128 hotel disponibili',
    'lp_mockStep3': "Costruzione dell'itinerario di 7 giorni",
    'lp_mockAgent': 'Ecco il tuo viaggio: 7 giorni a Lisbona con Alfama, Belém, una giornata a Sintra e 5 tavoli prenotati. Totale 1.042 €, 158 € sotto il tuo budget.',
    'lp_mockFlightTag': 'Volo andata e ritorno',
    'lp_mockFlightTitle': 'Parigi CDG → Lisbona',
    'lp_mockFlightSub': '2 h 45 · diretto · 12 ott.',
    'lp_mockHotelTag': 'Hotel',
    'lp_mockHotelTitle': 'Baixa Boutique Hotel',
    'lp_mockHotelSub': '4★ · centro storico · colazione inclusa',
    'lp_mockBudget': 'Budget totale',
    'lp_mockFloatingTag': 'Itinerario',
    'lp_mockFloatingValue': '7 giorni pianificati',
    'lp_mockFloating2Tag': 'Risparmio',
    'lp_mockFloating2Value': '158 € sotto budget',
    'lp_statsTitle': 'Collegati alle migliori fonti di viaggio',
    'lp_stat1': 'compagnie aeree collegate',
    'lp_stat2': 'hotel e alloggi confrontati',
    'lp_stat3': 'per un itinerario completo',
    'lp_stat4': 'voto medio dei viaggiatori',
    'lp_stepsTag': 'Come funziona',
    'lp_stepsTitle': 'Tre passaggi. Zero grattacapi.',
    'lp_stepsSubtitle': 'Niente più schede accumulate né fogli di calcolo. Tu descrivi, noi organizziamo.',
    'lp_step1Title': 'Descrivi cosa desideri',
    'lp_step1Desc': "In una frase: destinazione, date, budget, atmosfera. Come se parlassi a un amico che conosce ogni angolo del mondo.",
    'lp_step2Title': "L'IA compone il tuo viaggio",
    'lp_step2Desc': 'Cerca i voli, confronta gli hotel, seleziona le attività e assembla un itinerario coerente, ora per ora.',
    'lp_step3Title': 'Prenota con un clic',
    'lp_step3Desc': 'Tutto finisce nel carrello. Un unico pagamento sicuro e le conferme ti aspettano nel tuo spazio.',
    'lp_featuresTag': 'Funzionalità',
    'lp_featuresTitle': 'Un copilota di viaggio, non un motore di ricerca',
    'lp_featuresSubtitle': "Tutto ciò che serve per passare dal desiderio all'imbarco, riunito in un solo posto.",
    'lp_feat1Title': 'Un itinerario giorno per giorno, davvero pensato per te',
    'lp_feat1Desc': 'Ogni giornata è equilibrata: tempi di spostamento, orari di apertura, pause pranzo. Modificabile in qualsiasi momento con un semplice messaggio.',
    'lp_feat1Day1': 'Giorno 1 · Alfama e miradouros',
    'lp_feat1Day1Detail': 'Tram 28, castello di São Jorge, cena con fado',
    'lp_feat1Day2': 'Giorno 2 · Belém',
    'lp_feat1Day2Detail': 'Monastero dos Jerónimos, pastéis de Belém',
    'lp_feat1Day3': 'Giorno 3 · Sintra',
    'lp_feat1Day3Detail': 'Palácio da Pena, Quinta da Regaleira',
    'lp_feat2Title': 'Voli in tempo reale',
    'lp_feat2Desc': 'Prezzi e disponibilità in diretta su centinaia di compagnie, senza aprire altre schede.',
    'lp_feat3Title': 'Hotel e indirizzi selezionati',
    'lp_feat3Desc': 'Alloggi scelti in base al tuo budget e al quartiere ideale, recensioni incluse.',
    'lp_feat4Title': 'Pagamento sicuro',
    'lp_feat4Desc': 'Voli, hotel e attività in un unico carrello, pagati in una sola volta con Stripe.',
    'lp_feat5Title': 'Budget sotto controllo',
    'lp_feat5Desc': 'Il totale si aggiorna in diretta: sai sempre a che punto sei prima di confermare.',
    'lp_feat6Title': 'Disponibile in 5 lingue',
    'lp_feat6Desc': 'ItinaryMe parla la tua lingua e si adatta automaticamente al tuo paese e alla tua valuta.',
    'lp_destTag': 'Ispirazione',
    'lp_destTitle': 'Dove vai quest\'anno?',
    'lp_destSubtitle': "Scegli una destinazione e l'IA costruisce il viaggio completo in pochi secondi.",
    'lp_destCta': 'Tutte le destinazioni',
    'lp_testiTag': 'Testimonianze',
    'lp_testiTitle': "Hanno lasciato pianificare all'IA",
    'lp_testi1': 'Ho descritto il mio viaggio in due frasi e ho ricevuto un itinerario di 10 giorni in Giappone meglio costruito di quello a cui avevo dedicato tre fine settimana.',
    'lp_testi1Name': 'Camille L.',
    'lp_testi1Role': 'Viaggio in Giappone, 10 giorni',
    'lp_testi2': "Il comparatore di voli integrato mi ha fatto risparmiare 240 € sui biglietti. E non ho mai lasciato l'app per prenotare.",
    'lp_testi2Name': 'Marc R.',
    'lp_testi2Role': 'Weekend a Barcellona',
    'lp_testi3': 'Viaggiare in quattro con due bambini era un rompicapo. Questa volta tornava tutto: orari, distanze, ristoranti adatti.',
    'lp_testi3Name': 'Amélie D.',
    'lp_testi3Role': 'Vacanza in famiglia in Portogallo',
    'lp_ctaTitle': 'Il tuo prossimo viaggio inizia adesso',
    'lp_ctaSubtitle': 'Crea il tuo primo itinerario gratuitamente. Paghi solo ciò che prenoti.',
    'lp_ctaButton': 'Crea il mio itinerario',
    'lp_ctaSecondary': 'Guarda la demo',
    'lp_ctaPerk1': 'Senza carta di credito',
    'lp_ctaPerk2': 'Itinerario pronto in 60 secondi',
    'lp_ctaPerk3': 'Cancellazione secondo le condizioni del fornitore',
    // Footer translations
    'footer_about': 'Chi siamo',
    'footer_ourStory': 'La nostra storia',
    'footer_howItWorks': 'Come funziona',
    'footer_testimonials': 'Testimonianze',
    'footer_destinations': 'Destinazioni',
    'footer_popular': 'Popolari',
    'footer_bySeason': 'Per stagione',
    'footer_allDestinations': 'Tutte le destinazioni',
    'footer_contact': 'Contatti',
    'footer_contactUs': 'Contattaci',
    'footer_support': 'Supporto',
    'footer_faq': 'FAQ',
    'footer_copyright': '© 2025 ItinaryMe. Tutti i diritti riservati.',
    'footer_privacy': 'Privacy',
    'footer_terms': 'Termini',
    'footer_cookies': 'Cookie',
    'footer_tagline': 'Il tuo partner di fiducia per pianificare viaggi indimenticabili e personalizzati.',
  },
};

// Provider qui exposera la langue et les fonctions de traduction
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');
  
  // Fonction pour changer la langue et la sauvegarder dans localStorage
  const setLanguage = useCallback((newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('itinaryme-language', newLanguage);
    // Force un rafraîchissement subtil du DOM
    document.documentElement.lang = newLanguage;
    document.documentElement.setAttribute('data-language', newLanguage);
    console.log(`Langue changée pour: ${newLanguage}`);
  }, []);
  
  // Charger la langue depuis localStorage au premier rendu
  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('itinaryme-language') as Language;
      if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
        setLanguageState(savedLanguage);
        document.documentElement.lang = savedLanguage;
        document.documentElement.setAttribute('data-language', savedLanguage);
        console.log(`Langue chargée depuis localStorage: ${savedLanguage}`);
      } else {
        console.log('Aucune langue sauvegardée, détection automatique');
        detectLanguage();
      }
    } catch (e) {
      console.error('Erreur lors du chargement de la langue:', e);
      detectLanguage();
    }
  }, []);

  // Détecter la langue du navigateur ou à partir de l'API de géolocalisation
  const detectLanguage = async () => {
    try {
      // D'abord essayer la langue du navigateur
      const browserLang = navigator.language.split('-')[0];
      if (browserLang === 'fr' || browserLang === 'en' || browserLang === 'es' || browserLang === 'de' || browserLang === 'it') {
        setLanguage(browserLang as Language);
        console.log(`Langue du navigateur détectée: ${browserLang}`);
        return;
      }
      
      // Sinon essayer l'API de géolocalisation
      const response = await fetch('https://ipapi.co/json/');
      const data = await response.json();
      
      // Mapper le code pays vers une langue prise en charge
      const countryToLang: Record<string, Language> = {
        'FR': 'fr',
        'CA': 'fr',
        'BE': 'fr',
        'CH': 'fr',
        'US': 'en',
        'GB': 'en',
        'AU': 'en',
        'ES': 'es',
        'MX': 'es',
        'AR': 'es',
        'DE': 'de',
        'AT': 'de',
        'IT': 'it',
      };
      
      // Si le pays est reconnu, utiliser la langue correspondante
      if (data.country_code && countryToLang[data.country_code]) {
        setLanguage(countryToLang[data.country_code]);
        console.log(`Langue détectée par pays: ${countryToLang[data.country_code]}`);
      } else {
        // Par défaut, utiliser le français
        setLanguage('fr');
        console.log('Langue par défaut: français');
      }
    } catch (error) {
      console.error('Erreur lors de la détection de la langue:', error);
      // Utiliser le français par défaut en cas d'erreur
      setLanguage('fr');
    }
  };
  
  // Fonction améliorée de traduction
  const t = useCallback((key: string): string => {
    // Vérifier si la clé existe dans les traductions
    if (translations[language] && key in translations[language]) {
      return translations[language][key];
    }
    
    // Si non trouvée dans la langue actuelle, essayer en français
    if (language !== 'fr' && translations['fr'] && key in translations['fr']) {
      console.warn(`Traduction manquante pour "${key}" en ${language}, utilisation du français.`);
      return translations['fr'][key];
    }
    
    // Retourner la clé comme fallback si aucune traduction n'est trouvée
    console.warn(`Clé de traduction non trouvée: ${key}`);
    return key;
  }, [language]);
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook personnalisé pour utiliser le contexte de langue
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage doit être utilisé à l'intérieur d'un LanguageProvider");
  }
  return context;
} 