'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { interpretTravelRequest, detectBasicTravelInfo } from '@/ai/flows/interpret-travel-request';
import { analyzeBrowserContent } from '@/ai/flows/analyze-browser-content';
import { doc, getDoc, updateDoc, getFirestore, serverTimestamp, addDoc, collection, getDocs, deleteDoc, query, where } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useAuth } from '@/hooks/useAuth';
import { useBrowserAgent, BrowserAgentResult, BrowserAgentTask } from '@/hooks/useBrowserAgent';
import { useTrip } from '@/hooks/useTrip';
import { Pencil, Save, FileText, Plus, Calendar, MapPin, Users, AlertCircle, Trash2, LinkIcon, Send, Globe, Search, X } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Trip, Note, ChatMessage, MapPoint, TravelEvent, TravelItinerary } from '@/lib/types';
import * as noteService from '@/services/noteService';
import { TripSelector } from '@/components/TripSelector';
import { TravelForm } from '@/components/TravelForm';
import { Dialog } from '@/components/ui/dialog';
import { MessageItem } from './MessageItem';
import { BrowserAgent } from '@/ai/browserAgent';
import { createNote } from '@/services/noteService';
import { Ollama as LangchainOllama } from '@langchain/ollama';
import { webSearch } from '@/services/serpApi';

'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { interpretTravelRequest, detectBasicTravelInfo } from '@/ai/flows/interpret-travel-request';
import { analyzeBrowserContent } from '@/ai/flows/analyze-browser-content';
import { doc, getDoc, updateDoc, getFirestore, serverTimestamp, addDoc, collection, getDocs, deleteDoc, query, where } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useAuth } from '@/hooks/useAuth';
import { useBrowserAgent, BrowserAgentResult, BrowserAgentTask } from '@/hooks/useBrowserAgent';
import { useTrip } from '@/hooks/useTrip';
import { Pencil, Save, FileText, Plus, Calendar, MapPin, Users, AlertCircle, Trash2, LinkIcon, Send, Globe, Search, X } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Trip, Note, ChatMessage, MapPoint, TravelEvent, TravelItinerary } from '@/lib/types';
import * as noteService from '@/services/noteService';
import { TripSelector } from '@/components/TripSelector';
import { TravelForm } from '@/components/TravelForm';
import { Dialog } from '@/components/ui/dialog';
import { MessageItem } from './MessageItem';
import { BrowserAgent } from '@/ai/browserAgent';
import { createNote } from '@/services/noteService';
import { Ollama as LangchainOllama } from '@langchain/ollama';
import { webSearch } from '@/services/serpApi'; 